/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ddda.erp.gui;

import ddda.erp.objetos.CuerpoPedido;
import ddda.erp.objetos.Producto;
import ddda.erp.objetos.Proveedor;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Daniel
 */
public class JPGPedidosAdmin extends javax.swing.JPanel {

    CuerpoPedido cp;
    Producto pro;
    Proveedor prov;
    ArrayList<Producto> misPro = new ArrayList();
    ArrayList<Proveedor> misProv = new ArrayList();
    ArrayList<CuerpoPedido> alCp = new ArrayList();
    DefaultTableModel model;
    DefaultTableModel modeloConsulta;

    /**
     * Creates new form JPGPedidosEmp
     */
    public JPGPedidosAdmin() {
        initComponents();
        model = (DefaultTableModel) jtAddPedido.getModel();
        model.setRowCount(0);
        modeloConsulta = (DefaultTableModel) jtaConsPedido.getModel();
        modeloConsulta.setRowCount(0);
        String stringId;
        int idProv;
        int idCuerpoPed;
        try {
            Producto.mostrarProducto(misPro);
            for (int i = 0; i < misPro.size(); i++) {
                pro = (Producto) misPro.get(i);
                stringId = pro.getNombre_prod();
                System.out.println(stringId);
                jcbAddPedido.addItem(stringId);
            }
            Proveedor.mostrarProveedor(misProv);
            for (int i = 0; i < misProv.size(); i++) {
                prov = (Proveedor) misProv.get(i);
                idProv = prov.getIdProveedor();
                jcbProvPedidos.addItem(String.valueOf(idProv));
            }
            CuerpoPedido.mostrarCuerpoPedido(alCp);
            for (int i = 0; i < alCp.size(); i++) {
                cp = (CuerpoPedido) alCp.get(i);
                idCuerpoPed = cp.getIdPedido();
                jcbModIdCabPedido.addItem(String.valueOf(idCuerpoPed));
                jcbConsIdPedido.addItem(String.valueOf(idCuerpoPed));
                jcbBajaIdPedido.addItem(String.valueOf(idCuerpoPed));
            }

        } catch (SQLException ex) {
            Logger.getLogger(JPGPedidosAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jbAddPedido = new javax.swing.JButton();
        jbAddProducto = new javax.swing.JButton();
        jcbAddPedido = new javax.swing.JComboBox<>();
        jsAddPedido = new javax.swing.JSpinner();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtAddPedido = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jcbProvPedidos = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jbModificar = new javax.swing.JButton();
        jspModPedido = new javax.swing.JSpinner();
        jcbModPedido = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jcbModIdCabPedido = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jtfModDescPed = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jbBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaConsPedido = new javax.swing.JTable();
        jcbConsIdPedido = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jcbBajaIdPedido = new javax.swing.JComboBox<>();
        jbEliminarCabeceraPedido = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jcbBajaIdCuerpoPed = new javax.swing.JComboBox<>();
        jbBorrarCuerpoPedido = new javax.swing.JButton();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jLabel1.setText("ID de Producto:");

        jLabel3.setText("Cantidad:");

        jbAddPedido.setText("Añadir Pedido");
        jbAddPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAddPedidoActionPerformed(evt);
            }
        });

        jbAddProducto.setText("Añadir Producto");
        jbAddProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAddProductoActionPerformed(evt);
            }
        });

        jcbAddPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbAddPedidoActionPerformed(evt);
            }
        });

        jtAddPedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "idProducto", "idProveedor", "Cantidad", "Precio", "Descripcion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jtAddPedido);

        jLabel8.setText("Proveedores:");

        jcbProvPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbProvPedidosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(191, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jbAddProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(60, 60, 60)
                                    .addComponent(jbAddPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jcbProvPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jcbAddPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(29, 29, 29)
                                    .addComponent(jLabel3))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jsAddPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(183, 183, 183))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbAddPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jsAddPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jcbProvPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAddProducto)
                    .addComponent(jbAddPedido))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
        );

        jTabbedPane1.addTab("Alta Pedido", jPanel2);

        jLabel4.setText("Id Cuerpo Pedido:");

        jLabel6.setText("Cantidad:");

        jbModificar.setText("Modificar Pedido");
        jbModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModificarActionPerformed(evt);
            }
        });

        jcbModPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbModPedidoActionPerformed(evt);
            }
        });

        jLabel2.setText("ID Cabecera Pedido:");

        jcbModIdCabPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbModIdCabPedidoActionPerformed(evt);
            }
        });

        jLabel9.setText("Descripcion:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel9))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcbModPedido, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcbModIdCabPedido, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jspModPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfModDescPed))
                .addContainerGap(251, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jcbModIdCabPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jcbModPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jtfModDescPed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jspModPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jbModificar)
                .addContainerGap(189, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Modificar Pedido", jPanel1);

        jLabel7.setText("ID Pedido:");

        jbBuscar.setText("Buscar Pedido");
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });

        jtaConsPedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "idPedido", "idProducto", "Descripcion", "Cantidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtaConsPedido);

        jcbConsIdPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbConsIdPedidoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(45, 45, 45)
                        .addComponent(jcbConsIdPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jbBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(148, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jcbConsIdPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbBuscar))
                .addGap(60, 60, 60)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(208, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Consulta Pedido", jPanel3);

        jLabel5.setText("Id Cabecera Pedido:");

        jcbBajaIdPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbBajaIdPedidoActionPerformed(evt);
            }
        });

        jbEliminarCabeceraPedido.setText("Eliminar Cabecera Pedido");
        jbEliminarCabeceraPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarCabeceraPedidoActionPerformed(evt);
            }
        });

        jLabel10.setText("Id Cuerpo Pedido:");

        jbBorrarCuerpoPedido.setText("Eliminar Cuerpo Pedido");
        jbBorrarCuerpoPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBorrarCuerpoPedidoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel10))
                .addGap(45, 45, 45)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jcbBajaIdPedido, 0, 103, Short.MAX_VALUE)
                    .addComponent(jcbBajaIdCuerpoPed, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbEliminarCabeceraPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbBorrarCuerpoPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jcbBajaIdPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbEliminarCabeceraPedido))
                .addGap(23, 23, 23)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jcbBajaIdCuerpoPed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbBorrarCuerpoPedido))
                .addContainerGap(349, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Baja Pedido", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbAddProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAddProductoActionPerformed
        // TODO add your handling code here:
        String nombre = jcbAddPedido.getSelectedItem().toString();
        int cantidad = (int) jsAddPedido.getValue();
        int precio = 0;
        String idProv = jcbProvPedidos.getSelectedItem().toString();
        String desc = null;
        for (int i = 0; i < misPro.size(); i++) {
            pro = misPro.get(i);
            if (pro.getNombre_prod().equals(nombre) == true) {
                precio = pro.getPrecio_prod() * cantidad;
                desc = pro.getDescripcion_prod();
            }
        }
        model.addRow(new Object[]{(String) nombre, (String) idProv, (int) cantidad, (int) precio, (String) desc});
    }//GEN-LAST:event_jbAddProductoActionPerformed

    private void jcbAddPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbAddPedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbAddPedidoActionPerformed

    private void jbAddPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAddPedidoActionPerformed
        // TODO add your handling code here:
        int cols = jtAddPedido.getColumnCount();
        int fils = jtAddPedido.getRowCount();
        String nombre;
        String nomProd;
        int cantidad;
        int precio = 0;
        String idProv = null;
        int idPedido = 0;
        String descProd;
        CuerpoPedido cp = new CuerpoPedido();
        for (int i = 0; i < fils; i++) {
            idProv = (String) jtAddPedido.getValueAt(i, 1);
            precio = precio + (int) jtAddPedido.getValueAt(i, 3);
            for (int j = 0; j < cols; j++) {
            }
        }
        try {
            cp.crearCabeceraPedido(precio, idProv);
            idPedido = cp.recuperarIdPedido();
        } catch (SQLException ex) {
            Logger.getLogger(JPGPedidosAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
        for (int i = 0; i < fils; i++) {
            nomProd = (String) jtAddPedido.getValueAt(i, 0);
            int idProducto = 0;
            for (int k = 0; k < misPro.size(); k++) {
                pro = misPro.get(i);
                if (pro.getNombre_prod().equals(nomProd) == true) {
                    idProducto = pro.getIdProducto();
                }
            }
            cantidad = (int) jtAddPedido.getValueAt(i, 2);
            descProd = (String) jtAddPedido.getValueAt(i, 4);
            cp = new CuerpoPedido(idProducto, descProd, cantidad);
            try {
                cp.crearCuerpoPedido(idPedido);
            } catch (SQLException ex) {
                Logger.getLogger(JPGPedidosAdmin.class.getName()).log(Level.SEVERE, null, ex);
            }
            for (int j = 0; j < cols; j++) {
            }

        }
    }//GEN-LAST:event_jbAddPedidoActionPerformed

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        String stringId;
        int idProv;
        int idCuerpoPed;
        jcbAddPedido.setModel(new DefaultComboBoxModel());
        jcbProvPedidos.setModel(new DefaultComboBoxModel());
        jcbModIdCabPedido.setModel(new DefaultComboBoxModel());
        jcbConsIdPedido.setModel(new DefaultComboBoxModel());
        jcbBajaIdPedido.setModel(new DefaultComboBoxModel());
        try {
            Producto.mostrarProducto(misPro);
            for (int i = 0; i < misPro.size(); i++) {
                pro = (Producto) misPro.get(i);
                stringId = pro.getNombre_prod();
                System.out.println(stringId);
                jcbAddPedido.addItem(stringId);
            }
            Proveedor.mostrarProveedor(misProv);
            for (int i = 0; i < misProv.size(); i++) {
                prov = (Proveedor) misProv.get(i);
                idProv = prov.getIdProveedor();
                jcbProvPedidos.addItem(String.valueOf(idProv));
            }
            CuerpoPedido.mostrarCuerpoPedido(alCp);
            for (int i = 0; i < alCp.size(); i++) {
                cp = (CuerpoPedido) alCp.get(i);
                idCuerpoPed = cp.getIdPedido();
                jcbModIdCabPedido.addItem(String.valueOf(idCuerpoPed));
                jcbConsIdPedido.addItem(String.valueOf(idCuerpoPed));
                jcbBajaIdPedido.addItem(String.valueOf(idCuerpoPed));
            }

        } catch (SQLException ex) {
            Logger.getLogger(JPGPedidosAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void jcbProvPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbProvPedidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbProvPedidosActionPerformed

    private void jcbModIdCabPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbModIdCabPedidoActionPerformed
        // TODO add your handling code here:
        CuerpoPedido miCp;
        ArrayList<CuerpoPedido> misCp = new ArrayList();
        int idCab = 0;

        int idPed = Integer.parseInt(jcbModIdCabPedido.getSelectedItem().toString());
        try {
            misCp = CuerpoPedido.mostrarCuerpoPedidoID(idPed);
            for (int i = 0; i < misCp.size(); i++) {
                miCp = (CuerpoPedido) misCp.get(i);
                idCab = miCp.getIdProducto();
                jcbModPedido.addItem(String.valueOf(idCab));
            }
        } catch (SQLException ex) {
            Logger.getLogger(JPGPedidosAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jcbModIdCabPedidoActionPerformed

    private void jcbModPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbModPedidoActionPerformed
        // TODO add your handling code here:
        CuerpoPedido miCp;
        ArrayList<CuerpoPedido> misCp = new ArrayList();
        int idProd = Integer.parseInt(jcbModPedido.getSelectedItem().toString());
        int idPed = Integer.parseInt(jcbModIdCabPedido.getSelectedItem().toString());
        String desc = null;
        int cantidad = 0;
        try {
            misCp = CuerpoPedido.mostrarCuerpoPedidoIDProd(idProd, idPed);
            for (int i = 0; i < misCp.size(); i++) {
                miCp = (CuerpoPedido) misCp.get(i);
                desc = miCp.getDescripcion_cup();
                cantidad = miCp.getCantidad_cup();
            }
            jtfModDescPed.setText(desc);
            jspModPedido.setValue(cantidad);
        } catch (SQLException ex) {
            Logger.getLogger(JPGPedidosAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jcbModPedidoActionPerformed

    private void jbModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModificarActionPerformed
        // TODO add your handling code here:
        int idProducto = Integer.parseInt(jcbModPedido.getSelectedItem().toString());
        int idCabecera = Integer.parseInt(jcbModIdCabPedido.getSelectedItem().toString());
        cp.setIdPedido(idCabecera);
        cp.setIdProducto(idProducto);
        cp.setDescripcion_cup(jtfModDescPed.getText());
        cp.setCantidad_cup((int) jspModPedido.getValue());
        try {
            cp.modificarCuerpoPedido(idProducto, idCabecera);
        } catch (SQLException ex) {
            Logger.getLogger(JPGPedidosAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbModificarActionPerformed

    private void jcbConsIdPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbConsIdPedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbConsIdPedidoActionPerformed

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
        // TODO add your handling code here:
        CuerpoPedido miCp;
        ArrayList<CuerpoPedido> misCp = new ArrayList();
        int idCab = 0;
        int idProd = 0;
        String descrip = null;
        int cantidad = 0;

        int idPed = Integer.parseInt(jcbConsIdPedido.getSelectedItem().toString());
        try {
            misCp = CuerpoPedido.mostrarCuerpoPedidoID(idPed);
            for (int i = 0; i < misCp.size(); i++) {
                miCp = (CuerpoPedido) misCp.get(i);
                idCab = miCp.getIdPedido();
                idProd = miCp.getIdProducto();
                descrip = miCp.getDescripcion_cup();
                cantidad = miCp.getCantidad_cup();
                modeloConsulta.addRow(new Object[]{(int) idCab, (int) idProd, (String) descrip, (int) cantidad});
            }
        } catch (SQLException ex) {
            Logger.getLogger(JPGPedidosAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbBuscarActionPerformed

    private void jcbBajaIdPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbBajaIdPedidoActionPerformed
        // TODO add your handling code here:
        CuerpoPedido miCp;
        ArrayList<CuerpoPedido> misCp = new ArrayList();
        int idCab = 0;
        int idPed = Integer.parseInt(jcbBajaIdPedido.getSelectedItem().toString());
        try {
            misCp = CuerpoPedido.mostrarCuerpoPedidoID(idPed);
            for (int i = 0; i < misCp.size(); i++) {
                miCp = (CuerpoPedido) misCp.get(i);
                idCab = miCp.getIdProducto();
                jcbBajaIdCuerpoPed.addItem(String.valueOf(idCab));
            }
        } catch (SQLException ex) {
            Logger.getLogger(JPGPedidosAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jcbBajaIdPedidoActionPerformed

    private void jbEliminarCabeceraPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarCabeceraPedidoActionPerformed
        // TODO add your handling code here:
        int idCabeceraPedido = 0;
        idCabeceraPedido = Integer.parseInt(jcbBajaIdPedido.getSelectedItem().toString());
        try {
            cp.borrarCabeceraPedidoID(idCabeceraPedido);
        } catch (SQLException ex) {
            Logger.getLogger(JPGPedidosAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbEliminarCabeceraPedidoActionPerformed

    private void jbBorrarCuerpoPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBorrarCuerpoPedidoActionPerformed
        // TODO add your handling code here:
        int idCabeceraPedido = 0;
        int idProductoPedido = 0;
        idCabeceraPedido = Integer.parseInt(jcbBajaIdPedido.getSelectedItem().toString());
        idProductoPedido = Integer.parseInt(jcbBajaIdCuerpoPed.getSelectedItem().toString());
        try {
            cp.borrarCuerpoPedidoID(idCabeceraPedido, idProductoPedido);
        } catch (SQLException ex) {
            Logger.getLogger(JPGPedidosAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbBorrarCuerpoPedidoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jbAddPedido;
    private javax.swing.JButton jbAddProducto;
    private javax.swing.JButton jbBorrarCuerpoPedido;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbEliminarCabeceraPedido;
    private javax.swing.JButton jbModificar;
    private javax.swing.JComboBox<String> jcbAddPedido;
    private javax.swing.JComboBox<String> jcbBajaIdCuerpoPed;
    private javax.swing.JComboBox<String> jcbBajaIdPedido;
    private javax.swing.JComboBox<String> jcbConsIdPedido;
    private javax.swing.JComboBox<String> jcbModIdCabPedido;
    private javax.swing.JComboBox<String> jcbModPedido;
    private javax.swing.JComboBox<String> jcbProvPedidos;
    private javax.swing.JSpinner jsAddPedido;
    private javax.swing.JSpinner jspModPedido;
    private javax.swing.JTable jtAddPedido;
    private javax.swing.JTable jtaConsPedido;
    private javax.swing.JTextField jtfModDescPed;
    // End of variables declaration//GEN-END:variables
}
