/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ddda.erp.gui;

import ddda.erp.objetos.Butaca;
import ddda.erp.objetos.Pelicula;
import ddda.erp.objetos.Reserva;
import ddda.erp.objetos.Sesion;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author danif
 */
public class JPGReservas extends javax.swing.JPanel {

    /**
     * Creates new form JPGReservas
     */
    public JPGReservas() {
        initComponents();
        int idPelicula;
        int idSesion;
        ArrayList<Sesion> misSesiones = new ArrayList();
        Sesion miSesion;
        try {
            Sesion.mostrarPeliculasSesiones(misSesiones);
            for (int i = 0; i < misSesiones.size(); i++) {
                miSesion = new Sesion();
                miSesion = misSesiones.get(i);
                idPelicula = miSesion.getIdPelicula();
                jcbReservaPelicula.addItem(String.valueOf(idPelicula));
            }
        } catch (SQLException ex) {
            Logger.getLogger(JPGCinesAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        misSesiones = new ArrayList();
        
        try {
            Sesion.mostrarSesiones(misSesiones);
            for (int i = 0; i < misSesiones.size(); i++) {
                miSesion = new Sesion();
                miSesion = misSesiones.get(i);
                idSesion = miSesion.getIdSesion();
                jcbConsultarIdPelicula.addItem(String.valueOf(idSesion));
            }
        } catch (SQLException ex) {
            Logger.getLogger(JPGReservas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jcbReservaPelicula = new javax.swing.JComboBox<>();
        jcbReservaSesion = new javax.swing.JComboBox<>();
        jbReservar = new javax.swing.JButton();
        jcbFilaBut = new javax.swing.JComboBox<>();
        jcbNumBut = new javax.swing.JComboBox<>();
        jbNoReservar1 = new javax.swing.JButton();
        jlEstBut = new javax.swing.JLabel();
        jbConsultar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jcbConsultarIdPelicula = new javax.swing.JComboBox<>();
        jbConsultarPelicula = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaMostrarConsultaReserva = new javax.swing.JTable();

        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jLabel1.setText("Selecciona una pelicula:");

        jLabel2.setText("Selecciona una sesion:");

        jLabel3.setText("Fila de butaca:");

        jLabel4.setText("Numero de butaca:");

        jcbReservaPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbReservaPeliculaActionPerformed(evt);
            }
        });

        jcbReservaSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbReservaSesionActionPerformed(evt);
            }
        });

        jbReservar.setText("Realizar Reserva");
        jbReservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbReservarActionPerformed(evt);
            }
        });

        jcbFilaBut.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6" }));
        jcbFilaBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbFilaButActionPerformed(evt);
            }
        });

        jcbNumBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcbNumButMouseClicked(evt);
            }
        });
        jcbNumBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbNumButActionPerformed(evt);
            }
        });

        jbNoReservar1.setText("Cancelar Reserva");
        jbNoReservar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNoReservar1ActionPerformed(evt);
            }
        });

        jlEstBut.setText("Estado Butaca");

        jbConsultar.setText("Consultar Estado");
        jbConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConsultarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jcbReservaSesion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcbFilaBut, javax.swing.GroupLayout.Alignment.LEADING, 0, 146, Short.MAX_VALUE)
                            .addComponent(jcbNumBut, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcbReservaPelicula, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jlEstBut, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jbReservar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbNoReservar1, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jbConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jcbReservaPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jcbReservaSesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jcbFilaBut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jcbNumBut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlEstBut))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbReservar)
                    .addComponent(jbConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbNoReservar1)
                .addContainerGap(150, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Gestionar Reservas", jPanel1);

        jLabel11.setText("Id Sesion:");

        jbConsultarPelicula.setText("Consultar Reserva");
        jbConsultarPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConsultarPeliculaActionPerformed(evt);
            }
        });

        jtaMostrarConsultaReserva.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id Butaca", "Id Sesion", "Id Sala", "Fila Butaca"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtaMostrarConsultaReserva);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(jcbConsultarIdPelicula, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jbConsultarPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(142, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(jcbConsultarIdPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jbConsultarPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(136, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Consulta Reserva", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbNoReservar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNoReservar1ActionPerformed
        int idPelicula = Integer.valueOf(jcbReservaPelicula.getSelectedItem().toString());
        int idSesion = Integer.valueOf(jcbReservaSesion.getSelectedItem().toString());
        int nButaca = Integer.valueOf(jcbNumBut.getSelectedItem().toString());
        int nFila = Integer.valueOf(jcbFilaBut.getSelectedItem().toString());

        Reserva miReserva = new Reserva(idPelicula, idSesion, nButaca, nFila);
        try {
            Reserva.borrarReserva(miReserva);
            JOptionPane.showMessageDialog(null, "Reserva cancelada","Informacion", JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException ex) {
            Logger.getLogger(JPGReservas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbNoReservar1ActionPerformed

    private void jcbNumButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbNumButActionPerformed

    }//GEN-LAST:event_jcbNumButActionPerformed

    private void jcbFilaButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbFilaButActionPerformed
        ArrayList misIdsButacas = new ArrayList();
        int idSesion = Integer.valueOf(jcbReservaSesion.getSelectedItem().toString());
        int nFila = Integer.valueOf(jcbFilaBut.getSelectedItem().toString());
        try {
            misIdsButacas = Reserva.getidButaca(idSesion, nFila);
        } catch (SQLException ex) {
            Logger.getLogger(JPGReservas.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (jcbNumBut.getItemCount() != 0) {
            jcbNumBut.removeAllItems();
        }
        for (int i = 0; i < misIdsButacas.size(); i++) {
            System.out.println("numeros But:" + misIdsButacas.get(i).toString());
            jcbNumBut.addItem(misIdsButacas.get(i).toString());
        }
    }//GEN-LAST:event_jcbFilaButActionPerformed

    private void jbReservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbReservarActionPerformed
        int idPelicula = Integer.valueOf(jcbReservaPelicula.getSelectedItem().toString());
        int idSesion = Integer.valueOf(jcbReservaSesion.getSelectedItem().toString());
        int nButaca = Integer.valueOf(jcbNumBut.getSelectedItem().toString());
        int nFila = Integer.valueOf(jcbFilaBut.getSelectedItem().toString());

        Reserva miReserva = new Reserva(idPelicula, idSesion, nButaca, nFila);
        try {
            Reserva.crearReserva(miReserva);
            JOptionPane.showMessageDialog(null, "Reserva realizada","Informacion", JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException ex) {
            Logger.getLogger(JPGReservas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbReservarActionPerformed

    private void jcbReservaSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbReservaSesionActionPerformed

    }//GEN-LAST:event_jcbReservaSesionActionPerformed

    private void jcbReservaPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbReservaPeliculaActionPerformed
        int idSesion;
        Sesion miSesion;
        ArrayList<Sesion> misSesiones = new ArrayList();
        jcbReservaSesion.removeAllItems();
        try {
            misSesiones = Sesion.mostrarSesionIdPelicula(Integer.valueOf(jcbReservaPelicula.getSelectedItem().toString()));
            for (int i = 0; i < misSesiones.size(); i++) {
                miSesion = new Sesion();
                miSesion = misSesiones.get(i);
                idSesion = miSesion.getIdSesion();
                jcbReservaSesion.addItem(String.valueOf(idSesion));
                //                jcbConsId.addItem(stringId);
                //                jcbBajaPeliID.addItem(stringId);
                //                jcbBajaPeliNom.addItem(nomPel);
            }
        } catch (SQLException ex) {
            Logger.getLogger(JPGCinesAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jcbReservaPeliculaActionPerformed

    private void jcbNumButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcbNumButMouseClicked
       

    }//GEN-LAST:event_jcbNumButMouseClicked

    private void jbConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConsultarActionPerformed
      int idSesion = Integer.valueOf(jcbReservaSesion.getSelectedItem().toString());
        int nButaca = Integer.valueOf(jcbNumBut.getSelectedItem().toString());
        int nFila = Integer.valueOf(jcbFilaBut.getSelectedItem().toString());
        try {
            if (Reserva.evaluarButaca(nButaca, idSesion, nFila) == true) {
                jlEstBut.setText("Ocupada");
            } else {
                jlEstBut.setText("Libre");
            }
        } catch (SQLException ex) {
            System.out.println("Error trycatch");
            Logger.getLogger(JPGReservas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbConsultarActionPerformed

    private void jbConsultarPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConsultarPeliculaActionPerformed
        DefaultTableModel model = (DefaultTableModel) jtaMostrarConsultaReserva.getModel();
        ArrayList<Butaca> misReservas = new ArrayList();
        Butaca miReserva = new Butaca();
        int idReserva = Integer.valueOf(jcbConsultarIdPelicula.getSelectedItem().toString());
        try {
            misReservas = Reserva.mostrarReservasId(idReserva);
            model.setRowCount(0);
            for(int i = 0; i < misReservas.size();i++){
                miReserva = misReservas.get(i);
                model.addRow(new Object[]{miReserva.getIdButaca(), miReserva.getIdSesion(), miReserva.getIdSala(), miReserva.getnFila()});
            }
        } catch (SQLException ex) {
            Logger.getLogger(JPGReservas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbConsultarPeliculaActionPerformed

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        int idPelicula;
        int idSesion;
        ArrayList<Sesion> misSesiones = new ArrayList();
        Sesion miSesion;
        jcbReservaPelicula.setModel(new DefaultComboBoxModel());
        jcbConsultarIdPelicula.setModel(new DefaultComboBoxModel());
        try {
            Sesion.mostrarPeliculasSesiones(misSesiones);
            for (int i = 0; i < misSesiones.size(); i++) {
                miSesion = new Sesion();
                miSesion = misSesiones.get(i);
                idPelicula = miSesion.getIdPelicula();
                jcbReservaPelicula.addItem(String.valueOf(idPelicula));
            }
        } catch (SQLException ex) {
            Logger.getLogger(JPGCinesAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        misSesiones = new ArrayList();
        
        try {
            Sesion.mostrarSesiones(misSesiones);
            for (int i = 0; i < misSesiones.size(); i++) {
                miSesion = new Sesion();
                miSesion = misSesiones.get(i);
                idSesion = miSesion.getIdSesion();
                jcbConsultarIdPelicula.addItem(String.valueOf(idSesion));
            }
        } catch (SQLException ex) {
            Logger.getLogger(JPGReservas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTabbedPane1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jbConsultar;
    private javax.swing.JButton jbConsultarPelicula;
    private javax.swing.JButton jbNoReservar1;
    private javax.swing.JButton jbReservar;
    private javax.swing.JComboBox<String> jcbConsultarIdPelicula;
    private javax.swing.JComboBox<String> jcbFilaBut;
    private javax.swing.JComboBox<String> jcbNumBut;
    private javax.swing.JComboBox<String> jcbReservaPelicula;
    private javax.swing.JComboBox<String> jcbReservaSesion;
    private javax.swing.JLabel jlEstBut;
    private javax.swing.JTable jtaMostrarConsultaReserva;
    // End of variables declaration//GEN-END:variables
}
